# Generated by Django 3.1 on 2020-08-06 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=50)),
                ('balances', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('mask', models.CharField(blank=True, max_length=10, null=True)),
                ('official_name', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=15, null=True)),
                ('subtype', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_owner', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.FloatField()),
                ('authorized_date', models.DateField(blank=True, null=True)),
                ('category', models.JSONField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('iso_currency_code', models.CharField(blank=True, max_length=15, null=True)),
                ('location', models.JSONField(blank=True, null=True)),
                ('merchant_name', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_channel', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_meta', models.JSONField(blank=True, null=True)),
                ('pending', models.NullBooleanField()),
                ('pending_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_code', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=25, null=True)),
                ('unofficial_currency_code', models.CharField(blank=True, max_length=15, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Item.account')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=50, unique=True)),
                ('access_token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('institute_name', models.CharField(blank=True, max_length=50, null=True)),
                ('available_products', models.JSONField(blank=True, null=True)),
                ('billed_products', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Item.item'),
        ),
    ]
